spring:
  datasource:
    url: jdbc:mysql://localhost:3306/todo_db
    username: user
    password: password
  jooq:
    sql-dialect: mysql
logging:
  level:
    org.jooq.tools.LoggerListener: DEBUG
    org.jooq.tools: DEBUG